Parameters:
  Domain:
    Type: String
  DataProduct:
    Type: String
  SourceSystem:
    Type: String
  ServiceName:
    Type: String
  LayerName:
    Type: String
  BucketName:
    Type: String
  Environment: 
    Type: String
  WorkFlowDescription:
    Type: String
  ConcurrentRunsSpecified:
    Type: String
    AllowedValues: [true, false]
  ConcurrentRuns:
    Type: Number
  State:
    Type: String
    
  TableName:
    Type: String
  TableArea:
    Type: String
  IngressToProcessTriggerDescription:
    Type: String
  ProcessToReadableTriggerDescription:
    Type: String


Conditions:
  SpecifyConcurrentRuns: !Equals [!Ref ConcurrentRunsSpecified, 'true']


Resources:


############################### Workflow ###########################

  JobsWorkFlow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: !Ref WorkFlowDescription
      MaxConcurrentRuns: 10
      #MaxConcurrentRuns: !If [SpecifyConcurrentRuns, !Ref ConcurrentRuns, !Ref "AWS::NoValue"]
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${TableArea}"
      Tags: 
        - BusinessProcess: "Direct-to-Customer"
        - FunctionalArea: "eCommerce"
        - Supplier: "Quantyca"


############################### Triggers ###########################

  IngressProcessTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${TableName}_raw_to_odm_${TableName}'
      Description: !Ref IngressToProcessTriggerDescription
      Name: !Sub "${Domain}_${SourceSystem}_from_${TableName}_raw_to_odm_${TableName}_${Environment}_trigger"
      Type: EVENT
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${TableArea}"
      Tags:
        - BusinessProcess: "Direct-to-Customer"
        - FunctionalArea: "eCommerce"
        - Supplier: "Quantyca"

  ProcessReadableTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${TableName}_odm_to_rel_${TableName}'
      Description: !Ref ProcessToReadableTriggerDescription
      Name: !Sub "${Domain}_${SourceSystem}_from_${TableName}_odm_to_rel_${TableName}_${Environment}_trigger"
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Ref '${Domain}_${SourceSystem}_from_${TableName}_raw_to_odm_${TableName}'
            LogicalOperator: EQUALS
            State: SUCCEEDED 
        Logical: AND
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${TableArea}"
      Tags:
        - BusinessProcess: "Direct-to-Customer"
        - FunctionalArea: "eCommerce"
        - Supplier: "Quantyca"


############################### RuleToStartWorkflow ###########################
  WorkflowStartRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Ref RuleDescription
      EventPattern:
        source:
          - "aws.appflow"
        resource:
          - !Sub "arn:aws:appflow:eu-west-1:592141405271:flow/${Domain}-from-${SourceSystem}-${TableArea}-to-${ServiceName}-${LayerName}-${BucketName}"
        detail-type:
         - "AppFlow Flow Execution Status"
        detail:
          status:
            - "Successful"
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${TableArea}-${Environment}-triggering-rule"
      State: !Ref State
      Targets:
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:592141405271:trigger/${Domain}_${SourceSystem}_from_${TableName}_raw_to_odm_${TableName}_${Environment}_trigger"
         Id: !Sub "${Domain}_${SourceSystem}_from_${TableName}_raw_to_odm_${TableName}_${Environment}_trigger"