AWSTemplateFormatVersion: '2010-09-09'

Parameters:  
  Domain:
    Type: String
    AllowedValues: [afs, bil, cst, cuc, del, dto, eco, fin, hre, iot, mat, pla, pro, pur, sls]
  SourceSystem:
    Type: String
    AllowedValues: [ago, cpm, hqd, hon, scp, qlk, slf, sap, tms, sno, sie]
  ReturnArea:
    Type: String
  ReturnArea:
    Type: String
  Environment:
    Type: String
    Description: Specifies the environment of the trigger
    AllowedValues: [tst, prd]

  WorkFlowDescription:
    Type: String
  EnableConcurrentRuns:
    Type: String
    AllowedValues: ['true', 'false']
  ConcurrentRuns:
    Type: Number
  RuleDescription:
    Type: String

  ReturnOrderTableName:
    Type: String
  ReturnOrderObjectName:
    Type: String

  ReturnOrderItemAdjustmentTableName:
    Type: String
  ReturnOrderItemAdjustmentObjectName:
    Type: String

  ReturnOrderLineItemTableName:
    Type: String
  ReturnOrderLineItemObjectName:
    Type: String

  RefundTableName:
    Type: String
  RefundObjectName:
    Type: String


Conditions:
  ConcurrentRunsEnabled: !Equals [EnableConcurrentRuns, 'true']


Resources:

#################################### Workflow ####################################

  FullfillmentWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: !Ref WorkFlowDescription 
      MaxConcurrentRuns:
      !If
      - ConcurrentRunsEnabled
      - !Ref ConcurrentRuns
      - !Ref "AWS::NoValue"
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### RuleToStartWorkflow ####################################

  WorkflowStartRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Ref RuleDescription
      ScheduleExpression: cron(0 * ? * MON-SUN *)
      Name: !Sub "dp-${Domain}-${DataProduct}-workflow-${ReturnArea}-${Environment}-triggering-rule"
      State: ENABLED
      Targets:
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_raw_to_odm_${ReturnOrderTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_raw_to_odm_${ReturnOrderTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_raw_to_odm_${ReturnOrderItemAdjustmentTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_raw_to_odm_${ReturnOrderItemAdjustmentTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_raw_to_odm_${ReturnOrderLineItemTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_raw_to_odm_${ReturnOrderLineItemTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${RefundTableName}_raw_to_odm_${RefundToPr ocessLayerTargetTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${RefundTableName}_raw_to_odm_${RefundTableName}_${Environment}_trigger' 

#################################### ReturnOrder ####################################

  ReturnOrderToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${ReturnOrderObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_raw_to_odm_${ReturnOrderTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_raw_to_odm_${ReturnOrderTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  ReturnOrderToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_raw_to_odm_${ReturnOrderTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${ReturnOrderObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_odm_to_rel_${ReturnOrderTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderTableName}_odm_to_rel_${ReturnOrderTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### ReturnOrderItemAdjustment ####################################

  ReturnOrderItemAdjustmentToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${ReturnOrderItemAdjustmentObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_raw_to_odm_${ReturnOrderItemAdjustmentTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_raw_to_odm_${ReturnOrderItemAdjustmentTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  ReturnOrderItemAdjustmentToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_raw_to_odm_${ReturnOrderItemAdjustmentTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${ReturnOrderItemAdjustmentObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_odm_to_rel_${ReturnOrderItemAdjustmentTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderItemAdjustmentTableName}_odm_to_rel_${ReturnOrderItemAdjustmentTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### ReturnOrderLineItem ####################################

  ReturnOrderLineItemToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${ReturnOrderLineItemObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_raw_to_odm_${ReturnOrderLineItemTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_raw_to_odm_${ReturnOrderLineItemTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  ReturnOrderLineItemToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_raw_to_odm_${ReturnOrderLineItemTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${ReturnOrderLineItemObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_odm_to_rel_${ReturnOrderLineItemTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ReturnOrderLineItemTableName}_odm_to_rel_${ReturnOrderLineItemTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### Refund ####################################

  RefundToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${RefundObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${RefundTableName}_raw_to_odm_${RefundTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${RefundTableName}_raw_to_odm_${RefundTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  RefundToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${RefundTableName}_raw_to_odm_${RefundTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${RefundObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${RefundTableName}_odm_to_rel_${RefundTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${RefundTableName}_odm_to_rel_${RefundTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${ReturnArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"