AWSTemplateFormatVersion: '2010-09-09'

Parameters:  
  Domain:
    Type: String
    AllowedValues: [afs, bil, cst, cuc, del, dto, eco, fin, hre, iot, mat, pla, pro, pur, sls]
  SourceSystem:
    Type: String
    AllowedValues: [ago, cpm, hqd, hon, scp, qlk, slf, sap, tms, sno, sie]
  DataProduct:
    Type: String
  OrderItemArea:
    Type: String
  Environment:
    Type: String
    Description: Specifies the environment of the trigger
    AllowedValues: [tst, prd]

  WorkFlowDescription:
    Type: String
  EnableConcurrentRuns:
    Type: String
    AllowedValues: ['true', 'false']
  ConcurrentRuns:
    Type: Number
  RuleDescription:
    Type: String

  OrderItemToProcessLayerTargetTableName:
    Type: String
  OrderItemToProcessLayerSourceTableName:
    Type: String
  OrderItemToRedshiftSourceTableName:
    Type: String
  OrderItemToRedshiftTargetTableName:
    Type: String
  OrderItemObjectName:
    Type: String

  OrderItemAdjustmentLineSummaryToProcessLayerSourceTableName:
    Type: String
  OrderItemAdjustmentLineSummaryToProcessLayerTargetTableName:
    Type: String
  OrderItemAdjustmentLineSummaryToRedshiftSourceTableName:
    Type: String
  OrderItemAdjustmentLineSummaryToRedshiftTargetTableName:
    Type: String
  OrderItemAdjustmentLineSummaryObjectName:
    Type: String
      
  OrderItemSummaryToProcessLayerSourceTableName:
    Type: String
  OrderItemSummaryToProcessLayerTargetTableName:
    Type: String
  OrderItemSummaryToRedshiftSourceTableName:
    Type: String
  OrderItemSummaryToRedshiftTargetTableName:
    Type: String
  OrderItemSummaryObjectName:
    Type: String
      
  ShipmentToProcessLayerSourceTableName:
    Type: String 
  ShipmentToProcessLayerTargetTableName:
    Type: String 
  ShipmentToRedshiftSourceTableName:
    Type: String
  ShipmentToRedshiftTargetTableName:
    Type: String
  ShipmentObjectName:
    Type: String
    

Conditions:
  ConcurrentRunsEnabled: !Equals [EnableConcurrentRuns, 'true']


Resources:

#################################### Workflow ####################################

  FullfillmentWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: !Ref WorkFlowDescription 
      MaxConcurrentRuns:
      !If
      - ConcurrentRunsEnabled
      - !Ref ConcurrentRuns
      - !Ref "AWS::NoValue"
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### RuleToStartWorkflow ####################################

  WorkflowStartRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Ref RuleDescription
      ScheduleExpression: cron(0 * ? * MON-SUN *)
      Name: !Sub "dp-${Domain}-${DataProduct}-workflow-${OrderItemArea}-${Environment}-triggering-rule"
      State: ENABLED
      Targets:
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderItemToProcessLayerSourceTableName}_raw_to_odm_${OrderItemToProcessLayerTargetTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${OrderItemToProcessLayerSourceTableName}_raw_to_odm_${OrderItemToProcessLayerTargetTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemAdjustmentLineSummaryToProcessLayerTargetTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemAdjustmentLineSummaryToProcessLayerTargetTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderItemSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemSummaryToProcessLayerTargetTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${OrderItemSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemSummaryToProcessLayerTargetTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_odm_to_rel_${ShipmentToProcessLayerTargetTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_odm_to_rel_${ShipmentToProcessLayerTargetTableName}_${Environment}_trigger'

#################################### OrderItem ####################################

  OrderItemToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderItemObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemToProcessLayerSourceTableName}_raw_to_odm_${OrderItemToProcessLayerTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderItemToProcessLayerSourceTableName}_raw_to_odm_${OrderItemToProcessLayerTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderItemToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Description: !Sub "trigger for ${OrderItemObjectName} job from process to readable layer"
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemToProcessLayerSourceTableName}_raw_to_odm_${OrderItemToProcessLayerTargetTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemToRedshiftSourceTableName}_odm_to_rel_${OrderItemToRedshiftTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderItemToRedshiftSourceTableName}_odm_to_rel_${OrderItemToRedshiftTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### OrderItemAdjustmentLineSummary ####################################

  OrderItemAdjustmentLineSummaryToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderItemAdjustmentLineSummaryObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemAdjustmentLineSummaryToProcessLayerTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemAdjustmentLineSummaryToProcessLayerTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderItemAdjustmentLineSummaryToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Description: !Sub "trigger for ${OrderItemAdjustmentLineSummaryObjectName} job from process to readable layer"
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemAdjustmentLineSummaryToProcessLayerTargetTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToRedshiftSourceTableName}_odm_to_rel_${OrderItemAdjustmentLineSummaryToRedshiftTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderItemAdjustmentLineSummaryToRedshiftSourceTableName}_odm_to_rel_${OrderItemAdjustmentLineSummaryToRedshiftTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### OrderItemSummary ####################################

  OrderItemSummaryToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderItemSummaryObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemSummaryToProcessLayerTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderItemSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemSummaryToProcessLayerTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderItemSummaryToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Description: !Sub "trigger for ${OrderItemSummaryObjectName} job from process to readable layer"
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemSummaryToProcessLayerSourceTableName}_raw_to_odm_${OrderItemSummaryToProcessLayerTargetTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderItemSummaryToRedshiftSourceTableName}_odm_to_rel_${OrderItemSummaryToRedshiftTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderItemSummaryToRedshiftSourceTableName}_odm_to_rel_${OrderItemSummaryToRedshiftTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### Shipment ####################################

  ShipmentToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${ShipmentObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_raw_to_odm_${ShipmentToProcessLayerTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_raw_to_odm_${ShipmentToProcessLayerTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  ShipmentToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Description: !Sub "trigger for ${ShipmentObjectName} job from process to readable layer"
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_raw_to_odm_${ShipmentToProcessLayerTargetTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_odm_to_rel_${ShipmentToProcessLayerTargetTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${ShipmentToProcessLayerSourceTableName}_odm_to_rel_${ShipmentToProcessLayerTargetTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderItemArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"