AWSTemplateFormatVersion: '2010-09-09'

Parameters:  
  Domain:
    Type: String
    AllowedValues: [afs, bil, cst, cuc, del, dto, eco, fin, hre, iot, mat, pla, pro, pur, sls]
  SourceSystem:
    Type: String
    AllowedValues: [ago, cpm, hqd, hon, scp, qlk, slf, sap, tms, sno, sie]
  DataProduct:
    Type: String
  OrderArea:
    Type: String
  Environment:
    Type: String
    Description: Specifies the environment of the trigger
    AllowedValues: [tst, prd]

  WorkFlowDescription:
    Type: String
  EnableConcurrentRuns:
    Type: String
    AllowedValues: ['true', 'false']
  ConcurrentRuns:
    Type: Number
  RuleDescription:
    Type: String

  OrderTableName:
    Type: String
  OrderObjectName:
    Type: String
  
  OrderAdjustmentGroupTableName:
    Type: String
  OrderAdjustmentGroupObjectName:
    Type: String
  
  OrderAdjustmentGroupSummaryTableName:
    Type: String
  OrderAdjustmentGroupSummaryObjectName:
    Type: String
  
  OrderPaymentSummaryTableName:
    Type: String
  OrderPaymentSummaryObjectName:
    Type: String
  
  OrderSummaryTableName:
    Type: String
  OrderSummaryObjectName:
    Type: String
  
  SalesChannelTableName:
    Type: String
  SalesChannelObjectName:
    Type: String


Conditions:
  ConcurrentRunsEnabled: !Equals [EnableConcurrentRuns, 'true']


Resources:

#################################### Workflow ####################################

  FullfillmentWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: !Ref WorkFlowDescription 
      MaxConcurrentRuns:
      !If
      - ConcurrentRunsEnabled
      - !Ref ConcurrentRuns
      - !Ref "AWS::NoValue"
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### RuleToStartWorkflow ####################################

  WorkflowStartRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Ref RuleDescription
      ScheduleExpression: cron(0 * ? * MON-SUN *)
      Name: !Sub "dp-${Domain}-${DataProduct}-workflow-${OrderArea}-${Environment}-triggering-rule"
      State: ENABLED
      Targets:
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderTableName}_raw_to_odm_${OrderTableName}_${Environment}_trigger"
         Id: !Sub "${Domain}_${SourceSystem}_from_${OrderTableName}_raw_to_odm_${OrderTableName}_${Environment}_trigger"
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_raw_to_odm_${OrderAdjustmentGroupTableName}_${Environment}_trigger"
         Id: !Sub "${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_raw_to_odm_${OrderAdjustmentGroupTableName}_${Environment}_trigger"
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_raw_to_odm_${OrderAdjustmentGroupSummaryTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_raw_to_odm_${OrderAdjustmentGroupSummaryTableName}_${Environment}_trigger'
        -
         Arn: !Sub 'arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_raw_to_odm_${OrderPaymentSummaryTableName}_${Environment}_trigger'
         Id: !Sub '${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_raw_to_odm_${OrderPaymentSummaryTableName}_${Environment}_trigger'
        -
         Arn: !Sub 'arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_raw_to_odm_${OrderSummaryTableName}_${Environment}_trigger'
         Id: !Sub '${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_raw_to_odm_${OrderSummaryTableName}_${Environment}_trigger'
        -
         Arn: !Sub 'arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${SalesChannelTableName}_raw_to_odm_${SalesChannelTableName}_${Environment}_trigger'
         Id: !Sub '${Domain}_${SourceSystem}_from_${SalesChannelTableName}_raw_to_odm_${SalesChannelTableName}_${Environment}_trigger'

#################################### Order ####################################

  OrderToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderTableName}_raw_to_odm_${OrderTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderTableName}_raw_to_odm_${OrderTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderTableName}_raw_to_odm_${OrderTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${OrderObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderTableName}_odm_to_rel_${OrderTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderTableName}_odm_to_rel_${OrderTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### OrderAdjustmentGroup ####################################

  OrderAdjustmentGroupToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderAdjustmentGroupObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_raw_to_odm_${OrderAdjustmentGroupTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_raw_to_odm_${OrderAdjustmentGroupTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderAdjustmentGroupToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_raw_to_odm_${OrderAdjustmentGroupTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${OrderAdjustmentGroupObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_odm_to_rel_${OrderAdjustmentGroupTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupTableName}_odm_to_rel_${OrderAdjustmentGroupTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### OrderAdjustmentGroupSummary ####################################

  OrderAdjustmentGroupSummaryToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderAdjustmentGroupSummaryObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_raw_to_odm_${OrderAdjustmentGroupSummaryTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_raw_to_odm_${OrderAdjustmentGroupSummaryTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderAdjustmentGroupSummaryToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate: 
        Conditions: 
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_raw_to_odm_${OrderAdjustmentGroupSummaryTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${OrderAdjustmentGroupSummaryObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_odm_to_rel_${OrderAdjustmentGroupSummaryTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderAdjustmentGroupSummaryTableName}_odm_to_rel_${OrderAdjustmentGroupSummaryTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### OrderPaymentSummary ####################################

  OrderPaymentSummaryToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderPaymentSummaryObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_raw_to_odm_${OrderPaymentSummaryTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_raw_to_odm_${OrderPaymentSummaryTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderPaymentSummaryToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_raw_to_odm_${OrderPaymentSummaryTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${OrderPaymentSummaryObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_odm_to_rel_${OrderPaymentSummaryTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderPaymentSummaryTableName}_odm_to_rel_${OrderPaymentSummaryTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### OrderSummary ####################################

  OrderSummaryToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${OrderSummaryObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_raw_to_odm_${OrderSummaryTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_raw_to_odm_${OrderSummaryTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  OrderSummaryToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_raw_to_odm_${OrderSummaryTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${OrderSummaryObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_odm_to_rel_${OrderSummaryTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${OrderSummaryTableName}_odm_to_rel_${OrderSummaryTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### SalesChannel ####################################

  SalesChannelToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${SalesChannelObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${SalesChannelTableName}_raw_to_odm_${SalesChannelTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${SalesChannelTableName}_raw_to_odm_${SalesChannelTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  SalesChannelToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${SalesChannelTableName}_raw_to_odm_${SalesChannelTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${SalesChannelObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${SalesChannelTableName}_odm_to_rel_${SalesChannelTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${SalesChannelTableName}_odm_to_rel_${SalesChannelTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${OrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"