AWSTemplateFormatVersion: '2010-09-09'

Parameters:  
  Domain:
    Type: String
    AllowedValues: [afs, bil, cst, cuc, del, dto, eco, fin, hre, iot, mat, pla, pro, pur, sls]
  SourceSystem:
    Type: String
    AllowedValues: [ago, cpm, hqd, hon, scp, qlk, slf, sap, tms, sno, sie]
  DataProduct:
    Type: String
  FulfillmentOrderArea:
    Type: String
  Environment:
    Type: String
    Description: Specifies the environment of the trigger
    AllowedValues: [tst, prd]

  WorkFlowDescription:
    Type: String
  EnableConcurrentRuns:
    Type: String
    AllowedValues: ['true', 'false']
  ConcurrentRuns:
    Type: Number
  RuleDescription:
    Type: String

  FulfillmentOrderTableName:
    Type: String
  FulfillmentOrderObjectName:
    Type: String

  FulfillmentOrderItemAdjustmentTableName:
    Type: String
  FulfillmentOrderItemAdjustmentObjectName:
    Type: String

  FulfillmentOrderLineItemTableName:
    Type: String
  FulfillmentOrderLineItemObjectName:
    Type: String


Conditions:
  ConcurrentRunsEnabled: !Equals [EnableConcurrentRuns, 'true']


Resources:

#################################### Workflow ####################################

  FullfillmentWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: !Ref WorkFlowDescription 
      MaxConcurrentRuns:
      !If
      - ConcurrentRunsEnabled
      - !Ref ConcurrentRuns
      - !Ref "AWS::NoValue"
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### RuleToStartWorkflow ####################################

  WorkflowStartRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: !Ref RuleDescription
      ScheduleExpression: cron(0 * ? * MON-SUN *)
      Name: !Sub "dp-${Domain}-${DataProduct}-workflow-${FulfillmentOrderArea}-${Environment}-triggering-rule"
      State: ENABLED
      Targets:
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceDest}_from_${FulfillmentOrderTableName}_raw_to_odm_${FulfillmentOrderTableName}_${Environment}_trigger"
         Id: !Sub "${Domain}_${SourceSystem}_from_${FulfillmentOrderTableName}_raw_to_odm_${FulfillmentOrderTableName}_${Environment}_trigger"
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_raw_to_odm_${FulfillmentOrderItemAdjustmentTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_raw_to_odm_${FulfillmentOrderItemAdjustmentTableName}_${Environment}_trigger'
        -
         Arn: !Sub "arn:aws:glue:${AWS::Region}:590184051506:trigger/${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_raw_to_odm_${FulfillmentOrderLineItemTableName}_${Environment}_trigger"
         Id: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_raw_to_odm_${FulfillmentOrderLineItemTableName}_${Environment}_trigger'

#################################### FulfillmentOrder ####################################

  FulfillmentOrderToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${FulfillmentOrderObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderTableName}_raw_to_odm_${FulfillmentOrderTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderTableName}_raw_to_odm_${FulfillmentOrderTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  FulfillmentOrderToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderTableName}_raw_to_odm_${FulfillmentOrderTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${FulfillmentOrderObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderTableName}_odm_to_rel_${FulfillmentOrderTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderTableName}_odm_to_rel_${FulfillmentOrderTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### FulfillmentOrderItemAdjustment ####################################

  FulfillmentOrderItemAdjustmentToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${FulfillmentOrderItemAdjustmentObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_raw_to_odm_${FulfillmentOrderItemAdjustmentTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_raw_to_odm_${FulfillmentOrderItemAdjustmentTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  FulfillmentOrderItemAdjustmentToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions:
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_raw_to_odm_${FulfillmentOrderItemAdjustmentTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${FulfillmentOrderItemAdjustmentObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_odm_to_rel_${FulfillmentOrderItemAdjustmentTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderItemAdjustmentTableName}_odm_to_rel_${FulfillmentOrderItemAdjustmentTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

#################################### FulfillmentOrderLineItem ####################################

  FulfillmentOrderLineItemToProcessLayerHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: EVENT
      Description: !Sub "trigger for ${FulfillmentOrderLineItemObjectName} job from ingress to process layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_raw_to_odm_${FulfillmentOrderLineItemTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_raw_to_odm_${FulfillmentOrderLineItemTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"

  FulfillmentOrderLineItemToRedshiftHourlyTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      Predicate:
        Conditions: 
          - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_raw_to_odm_${FulfillmentOrderLineItemTableName}'
          - LogicalOperator: EQUALS
          - State: SUCCEEDED
      Description: !Sub "trigger for ${FulfillmentOrderLineItemObjectName} job from process to readable layer"
      Actions:
        - JobName: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_odm_to_rel_${FulfillmentOrderLineItemTableName}'
          Arguments:
            '--job-bookmark-option': job-bookmark-enable   
      Name: !Sub '${Domain}_${SourceSystem}_from_${FulfillmentOrderLineItemTableName}_odm_to_rel_${FulfillmentOrderLineItemTableName}_${Environment}_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${FulfillmentOrderArea}" 
      Tags: 
        - Key: "BusinessProcess"
          Value: "Direct to Customer"
        - Key: "FunctionalArea"
          Value: "eCommerce"
        - Key: "Supplier"
          Value: "Quantyca"